### ISSUE TITLE
Segfault when running tests

### ISSUE THREAD

**Issue by tomelse** [thorstone25/qups#38]
![Screenshot](https://github.com/user-attachments/assets/3b0fe31c-4091-48ef-a30a-9c3a4fc82dbd)

I seem to get a segmentation fault when running the tests. I managed to get a screenshot before MATLAB closed (see attached) but I can't work out what is going wrong. Do you have any ideas?

**Comment by thorstone25** [comment]
I think there's something going on between with recent MATLAB and linux updates. The file that's failing `msfm2d()` is aa slightly modified version of published code from the [original](https://www.mathworks.com/matlabcentral/fileexchange/24531-accurate-fast-marching) library that's been around since 2011. About a month ago, it started failing on every linux system I've tried.

As of #36 (v1.2.0), the default initialization routines should avoid trying to recompile and use mex files. You would need to delete all the mex files in the `bin` directory first, and then it should work using the native implementation.

**Comment by tomelse** [comment]
Thanks! I'll try out the new version :)
